- name: Downloading Redis
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed

- name: Enabling Redis
  ansible.builtin.shell: dnf module enable redis:remi-6.2 -y

- name: Installing Redis
  ansible.builtin.yum:
    name: redis
    state: installed

- name: Updating Redis listen address
  ansible.builtin.replace:
    path: redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start Redis
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes
