- name: Copy MongoDB Yum Repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing MongoDB
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: Replacing listen address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting Mongodb
  ansible.builtin.service:
    name: mongod
    state: restarted
    enabled: yes