groups:
  - name: {{component}}
    rules:
      - alert: Service Down !!!
        expr: node_systemd_unit_state{name="{{env}}-{{component}}",exported_name = "{{service_name}}.service" ,state="active"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
  {% raw %}
  summary: "Service Down - [{{ $labels.name }}]"
  description: " Service {{$label.exported_name}} is down"
  {% endraw %}