- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Remove old HTTP Documents
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create HTTP Document Directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Downloading {{component}} Application content
  ansible.builtin.unarchive:
    src: "http://{{nexus_user}}:{{nexus_pass}}@172.31.11.118:8081/repository/{{component}}/{{component}}-{{version}}.zip"
    dest: /usr/share/nginx/html
    remote_src: yes
  vars:
    nexus_user: {{ lookup('aws_ssm', "nexus.user", region='us-east-1' ) }}
    nexus_pass: {{ lookup('aws_ssm', "nexus.pass", region='us-east-1' ) }}

- name: Copying config file to location
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/

- name: Starting Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes