- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    status: installed

- name: Remove old HTTP Documents
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create HTTP Document Directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory


- name: Downloading and extracting the frontend content
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes
