- name: Downloading yum repos
  ansible.builtin.shell: curl -s {{ item }} | bash
  loop:
    - https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh
    - https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh

- name: Install Erlang and RabbitMQ
  ansible.builtin.yum:
    name:
#      - erlang   #### Ignoring erlang installation due to error
      - rabbitmq-server
    state: installed

- name: Start RabbitMQ server
  ansible.builtin.systemd:
    name: rabbitmq-server
    daemon_reload: yes
    enabled: yes
    state: restarted

- name: Adding application user
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: "{{ lookup('aws_ssm', '{{env}}.rabbitmq.PASS', region='us-east-1')}}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
    tags: administrator


