- name: Copying Logstash configuration fie
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Restarting Logstash
  ansible.builtin.systemd:
    name: logstash
    state: restarted