- name: Downloading NodeJS
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Add application user
  ansible.builtin.user:
    name: roboshop

- name: Remove old app content
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create app Directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Downloading application content to directory
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/catalogue.zip
    dest: /app
    remote_src: yes

- name: Updating NodeJS
  community.general.npm:
    path: /app
    state: latest

- name: Copying systemD file
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system

- name: Starting Catalogue service
  ansible.builtin.systemd:
    name: catalogue
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Copy MongoDB Yum Repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing MongoDB
  ansible.builtin.yum:
    name: mongod-org-client
    state: installed

- name: Loading Schema
  community.mongodb.mongodb_shell:
    login_host: mongodb-dev.devpractice.online
    file: "/app/schema/catalogue.js"
    idempotent: yes

