- name: Downloading NodeJS
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Installing NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Adding the user
  ansible.builtin.user:
    name: roboshop

- name: Remove old Documents
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create new Directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Downloading Application content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/catalogue.zip
    dest: /app
    remote_src: yes

- name: Installing NPM
  npm:
    name: catalogue
    path: /app

- name: Copying systemD file
  ansible.builtin.copy:
    src: "catalogue.service"
    dest: /etc/systemd/system/catalogue.service

- name: Starting {{component}} service
  ansible.builtin.systemd:
    name: "catalogue"
    daemon_reload: yes
    enabled: yes
    state: restarted

- name: Copy MongoDB Yum Repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing MongoDB
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: Load Schema
  community.mongodb.mongodb_shell:
    login_host: mongodb-dev.devpractice.online
    file: "/app/schema/catalogue.js"
    idempotent: yes
