- name: Adding Prometheus Server
  ansible.builtin.include_tasks: server.yml
  when: prometheus == "server"

- name: Adding Prometheus Server
  ansible.builtin.include_tasks: exporter.yml
  when: prometheus == "exporter"