- name: Copying Prometheus config files
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml
  vars:
    labels:
    - {tag : "env", label: "environment"}
    - {tag: "Name", label: "name"}


- name: Restarting Prometheus
  ansible.builtin.systemd:
    name: prometheus.service
    state: restarted

- name: Copying template file
  ansible.builtin.template:
    src: grafana-dashboard.json
    dest: /tmp/grafana.json
    remote_src: yes

- name: Importing Grafana Dashboard
  community.grafana.grafana_dashboard:
    grafana_url: http://172.31.15.172:3000
    grafana_api_key: {{ "grafana_api_key" }}
    state: present
    overwrite: yes
    path: /tmp/grafana.json
