- name: Adding the user
  ansible.builtin.user:
    name: roboshop

- name: Remove old Documents
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create new Directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Downloading {{component}} Application content
  ansible.builtin.unarchive:
    src: http://admin:admin123@172.31.11.118:8081/repository/{{component}}/{{component}}-{{version}}.zip
    dest: /app
    remote_src: yes



