- name: Adding the user
  ansible.builtin.user:
    name: roboshop

- name: Remove old Documents
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create new Directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Downloading {{component}} Application content
  ansible.builtin.unarchive:
    src: http://{{nexus_user}}:{{nexus_password}}@172.31.11.118:8081/#browse/browse/{{component}}/{{component}}-{{version}}.zip
    dest: /app
    remote_src: yes
  vars:
    nexus_user: {{ lookup('aws_ssm', "nexus.user", region='us-east-1') }}
    nexus_password: {{ lookup('aws_ssm', "nexus.password", region='us-east-1') }}


