- name: Adding the user
  ansible.builtin.user:
    name: roboshop

- name: Remove old Documents
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create new Directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Downloading {{component}} Application content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /app
    remote_src: yes