- name: Install MYSQL client
  ansible.builtin.yum:
    name:
       - mysql
       - python3-PyMySQL
    state: installed

- name: Check Schema is Loaded or not
  community.mysql.mysql_info:
    filter:
      - databases
    exclude_fields: db_size
    return_empty_dbs: false
    login_host: "{{ lookup('aws_ssm', '{{env}}.rds.ENDPOINT', region='us-east-1' ) }}"
    login_user: "{{ lookup('aws_ssm', '{{env}}.rds.DB_ADMIN_USER', region='us-east-1' ) }}"
    login_password: "{{ lookup('aws_ssm', '{{env}}.rds.DB_ADMIN_PASS', region='us-east-1' ) }}"
  register: out


- name: Load MySQL
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/schema/{{component}}.sql
    login_host: "{{ lookup('aws_ssm', '{{env}}.rds.ENDPOINT', region='us-east-1')}}"
    login_user: "{{ lookup('aws_ssm', '{{env}}.rds.DB_ADMIN_USER', region='us-east-1')}}"
    login_password: "{{ lookup('aws_ssm', '{{env}}.rds.DB_ADMIN_PASS', region='us-east-1')}}"
  when: "'cities' not in out.databases"