- name: Install MYSQL client
  ansible.builtin.yum:
    name:
       - mysql
       - python3-PyMySQL
    state: installed

- name: Load MySQL
  community.mysql.mysql_db:
    state: import
    name: mysql
    target: /app/schema/{{component}}.sql
    login_host: "{{ lookup('aws_ssm', '{{env}}.rds.ENDPOINT', region='us-east-1')}}"
    login_user: "{{ lookup('aws_ssm', '{{env}}.rds.DB_ADMIN_USER', region='us-east-1')}}"
    login_password: "{{ lookup('aws_ssm', '{{env}}.rds.DB_ADMIN_PASS', region='us-east-1')}}"