- name: Downloading NodeJS
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Installing NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Adding the user
  ansible.builtin.user:
    name: roboshop

- name: Remove old Documents
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create new Directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Downloading {{component}} Application content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /app
    remote_src: yes

- name: Installing NPM
  npm:
    name: catalogue
    path: /app

- name: Copying systemD file
  ansible.builtin.copy:
    src: "{{component}}.service"
    dest: /etc/systemd/system/{{component}}.service

- name: Starting {{component}} service
  ansible.builtin.systemd:
    name: "{{component}}"
    daemon_reload: yes
    enabled: yes
    state: restarted

- name: Importing Schema
  import_tasks: "{{schema_type}}"-schema.yml
  when: schema_load


