- name: Downloading NodeJS
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Installing NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: App Pre-requisites
  ansible.builtin.include_tasks: app-prereq.yml

- name: Installing NPM
  npm:
    name: catalogue
    path: /app

- name : Downloading DOcDB content
  ansible.builtin.get_url:
    url: https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem
    dest: /app/{{component}}/rds-combined-ca-bundle.pem\
  when: schema_load


- name: SystemD
  ansible.builtin.include_tasks: systemd.yml

- name: Importing Schema
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yml"
  when: schema_load


