- name: Downloading NodeJS
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: App Pre-Req
  ansible.builtin.include_tasks: "appprereq.yml"

- name: Install Nodejs dependencies
  community.general.npm:
    path: /app
    state: latest

- name: Install Schema
  ansible.builtin.include_tasks: "mongo-schema.yml"

- name: Start {{component}}
  ansible.builtin.include_tasks: "systemd.yml"