route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
receivers:
  - name: "email"
    email_configs:
      - to: "palakurthyk95@gmail.com"      # you@example.com
        from: "palakurthyk95@gmail.com"  # alertmanager@example.com
        smarthost: "email-smtp.${SES_SMTP_REGION}.amazonaws.com:587"
        auth_username: "{{ lookup('aws_ssm', 'smtp.user', region='us-east-1')}}"
        auth_password: "{{ lookup('aws_ssm', 'smtp.pass', region='us-east-1')}}"
        require_tls: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']